import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const work_Sans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Marvel Heroes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={work_Sans.className}>{children}</body>
    </html>
  );
}
